name: kreasi
description: Aplikasi GO Kreasi 4.0 merupakan aplikasi dari Ganesha Operation dalam rangka digitalisasi produk Ganesha Operation. Di peruntukkan untuk Siswa dan Orang Tua Siswa.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+47

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #flutter_device_identifier: ^0.0.1
  unique_identifier: ^0.3.0
  chewie: ^1.7.0
  video_player: ^2.7.0
  visibility_detector: ^0.4.0+2
  isoweek: ^1.1.4
  timeline_tile: ^2.0.0
  jiffy: ^6.2.1
  animations: ^2.0.7
  adaptive_action_sheet: ^2.0.2
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.5
  timer_count_down: ^2.2.1
  dotted_border: ^2.0.0+3
  # UUID untuk menggantikan imei perangkat.
  uuid: ^3.0.6
  # Pada device_info_plus versi 4.0.0 ke atas,
  # androidId di hapus due to Google Play Policies
  device_info_plus: ^9.0.3
  encrypt: ^5.0.1
  equatable: ^2.0.5
  email_validator: ^2.1.17
#  expand_widget: ^3.1.1
  flash: ^3.0.5+1
  fl_chart: ^0.63.0
  flutter_svg: ^2.0.7
  firebase_core: ^2.15.1
  flutter_dotenv: ^5.1.0
  flutter_radar_chart: ^0.2.1
  flutter_form_builder: ^9.1.0
  html: ^0.15.4
  flutter_widget_from_html_core: ^0.10.3
  fwfh_cached_network_image: ^0.7.0+5
  fwfh_svg: ^0.8.0+2
  flutter_layout_grid: 2.0.4
#  flutter_html: 3.0.0-alpha.5
#  flutter_html_table: 3.0.0-alpha.3
  flutter_html: 3.0.0-beta.2
  flutter_html_table: 3.0.0-beta.2
  flutter_secure_storage: ^8.0.0
  flutter_math_fork: ^0.7.1
  # Untuk menggantikan flutter_secure_storage karena tidak stabil
  shared_preferences: ^2.2.0
  flutter_barcode_scanner: ^2.0.0
#  flutter_animation_progress_bar: ^2.3.1
  # flutter_cache_manager: ^3.3.0
  flutter_datetime_picker: ^1.5.1
  form_builder_validators: ^9.0.0
  flutter_local_notifications: ^15.1.0+1
  flutter_native_timezone: ^2.0.0
  geolocator: ^10.0.0
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  jwt_decoder: ^2.0.1
  mobile_scanner: ^3.4.1
  ntp: ^2.0.0
  provider: ^6.0.5
  photo_view: ^0.14.0
  path_provider: ^2.1.0
  package_info_plus: ^4.1.0
  permission_handler: ^10.4.3
  readmore: ^2.2.0
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  screenshot: ^2.1.0
  share_plus: ^7.1.0
  syncfusion_flutter_calendar: ^22.2.9
  syncfusion_flutter_pdfviewer: ^22.2.9
  scrollable_positioned_list: ^0.3.8
  timezone: ^0.9.0
  url_launcher: ^6.1.12
  otp: ^3.1.4
  base32: ^2.1.3
  # Run commands to generate splash screen.
  # 1) flutter clean
  # 2) flutter pub get
  # 3) flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.3.2
  webview_flutter: ^4.2.2
  pull_to_refresh: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.2
  change_app_package_name: ^1.1.0
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: 26fedcee4b0e6f7a85f65f1fb48834a21f57e970

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  background_image: assets/img/background_img.png
  image: assets/img/launcher.png
  branding: assets/img/branding.png
  branding_mode: bottom
  background_image_dark: assets/img/background_img.png
  image_dark: assets/img/launcher.png
  branding_dark: assets/img/branding.png
  android: true
  ios: true
  web: false
  fullscreen: true
  android_12:
    image: assets/img/android12splash.png
    color: "#ed323e"
    icon_background_color: "#FBFDFD"
    color_dark: "#be2832"
    icon_background_color_dark: "#FBFDFD"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
